### ISSUE TITLE
StyledText: IllegalArgumentException: Index out of bounds

### ISSUE THREAD

**Issue by buchen** [greipadmin/greip#28]
I am trying to use StyledText in my [Eclipse e4 RCP application](https://github.com/buchen/portfolio).

Problem: No text is displayed and when I move the mouse over the field, I get an IllegalArgumentException (see strack trace below).

I am essentially replacing ```Label``` with ```StyledLabel``` trying to print the following text:

```
20 <style fg="#008000">↑19</style> <style fg="#800000">↓1</style>
```

I also tried the text from the sample but I also get a rendering issue. As you can see on the screenshot, the second line is not printed correctly. If I remove the line break, nothing is displayed and I get the exception as above. 

<img width="479" alt="Bildschirmfoto 2019-05-05 um 20 46 50" src="https://user-images.githubusercontent.com/587976/57198851-1fb19080-6f78-11e9-8bed-ac42a5da46bd.png">

I am developing against the 2018-09 Eclipse repository (I am hesitant to update to a later version because Eclipse is remove support for 32bit versions).

Any idea what I am doing wrong?

The stack trace:

```
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4576)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.graphics.TextLayout.getStyle(TextLayout.java:1476)
	at org.greip.markup.MarkupText.getLinkAtLocation(MarkupText.java:169)
	at org.greip.label.StyledLabel.lambda$2(StyledLabel.java:126)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
```

My changes - see the replacement of Label by StyledText.

```patch
diff --git a/name.abuchen.portfolio.ui/META-INF/MANIFEST.MF b/name.abuchen.portfolio.ui/META-INF/MANIFEST.MF
index ad042fbb..56d86ee1 100644
--- a/name.abuchen.portfolio.ui/META-INF/MANIFEST.MF
+++ b/name.abuchen.portfolio.ui/META-INF/MANIFEST.MF
@@ -88,6 +88,7 @@ Import-Package: com.google.common.collect;version="23.5.0",
  org.eclipse.swt.layout,
  org.eclipse.swt.program,
  org.eclipse.swt.widgets,
+ org.greip.label,
  org.json.simple;version="1.1.1",
  org.json.simple.parser;version="1.1.1",
  org.osgi.framework;version="1.7.0",
diff --git a/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/TradesWidget.java b/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/TradesWidget.java
index 67f63cda..3406e55d 100644
--- a/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/TradesWidget.java
+++ b/name.abuchen.portfolio.ui/src/name/abuchen/portfolio/ui/views/dashboard/TradesWidget.java
@@ -17,6 +17,7 @@ import org.eclipse.swt.widgets.Label;
 import org.eclipse.ui.forms.events.HyperlinkAdapter;
 import org.eclipse.ui.forms.events.HyperlinkEvent;
 import org.eclipse.ui.forms.widgets.ImageHyperlink;
+import org.greip.label.StyledLabel;
 
 import com.ibm.icu.text.MessageFormat;
 
@@ -25,6 +26,7 @@ import name.abuchen.portfolio.snapshot.trades.Trade;
 import name.abuchen.portfolio.snapshot.trades.TradeCollector;
 import name.abuchen.portfolio.ui.Images;
 import name.abuchen.portfolio.ui.editor.PortfolioPart;
+import name.abuchen.portfolio.ui.util.Colors;
 import name.abuchen.portfolio.ui.views.trades.TradeDetailsView;
 import name.abuchen.portfolio.util.Interval;
 
@@ -34,7 +36,7 @@ public class TradesWidget extends WidgetDelegate<TradeDetailsView.Input>
     private PortfolioPart part;
 
     protected Label title;
-    protected Label indicator;
+    protected StyledLabel indicator;
 
     public TradesWidget(Widget widget, DashboardData dashboardData)
     {
@@ -55,7 +57,7 @@ public class TradesWidget extends WidgetDelegate<TradeDetailsView.Input>
         title.setBackground(container.getBackground());
         GridDataFactory.fillDefaults().grab(true, false).span(2, 1).applyTo(title);
 
-        indicator = new Label(container, SWT.NONE);
+        indicator = new StyledLabel(container, SWT.NONE);
         indicator.setFont(resources.getKpiFont());
         indicator.setBackground(container.getBackground());
         indicator.setText(""); //$NON-NLS-1$
@@ -88,8 +90,15 @@ public class TradesWidget extends WidgetDelegate<TradeDetailsView.Input>
 
         List<Trade> trades = input.getTrades();
         long positive = trades.stream().filter(t -> t.getIRR() > 0).count();
-        this.indicator.setText(
-                        MessageFormat.format("{0}   ↑{1} ↓{2}", trades.size(), positive, trades.size() - positive)); //$NON-NLS-1$
+        String text = MessageFormat.format(
+                        "{0} <style fg=\"" + Colors.toHex(Colors.DARK_GREEN) + "\">↑{1}</style> <style fg=\""
+                                        + Colors.toHex(Colors.DARK_RED) + "\">↓{2}</style>\n", //$NON-NLS-1$
+                        trades.size(), positive, 
+                        trades.size() - positive);
+        
+        System.out.println(text);
+        
+        this.indicator.setText(text);
     }
 
     @Override
```

BTW, great widgets - Calculator and ColorChooser is also something that I could use. 😄 👍

**Comment by greipadmin** [comment]
Thank you for the praise.

The three dots at the end of the displayed text indicate that the text was automatically trimmed. You use StyledLabel in a grid layout. Make sure that the StyledLabel has sufficient size for the text to be displayed.

I hope it helps.
Thomas

**Comment by buchen** [comment]
Okay, I understand the "Hello World" part. Will try without a second line later.

The other label "20  ↑19 ↓1" has more than enough space to display (and also shows fully when using ```Label```).

On the other hand, I do not necessarily have control how my users size their UI / Window. So having a IllegalArgumentException if the label is too long is awkward.

**Comment by greipadmin** [comment]
I have found the mistake and will build a new version on the weekend. Unfortunately, I do not get to that before.

**Comment by buchen** [comment]
Great! No hurry. I myself have no time immediately - I can also build it locally and test it with my project.

**Comment by greipadmin** [comment]
Great. Please close the issue if your test was successful.

**Comment by buchen** [comment]
Fixed it. Thanks.

There is a slightly different behavior if the label is an empty string. Even if the label is empty, the preferred size by ```org.eclipse.swt.widgets.Label``` seems to be based on the font size. For the ```StyledLabel```, this seems to be smaller (the default size?). I can workaround this by setting the text to *one space* instead of an empty String. If that rings a bell, please let me know. Otherwise I will see if I can find out why this behavior is different.

**Comment by greipadmin** [comment]
I checked this with the height again. For me, the StyledLabel has the height of the font. Can you demonstrate your problem with a simple code example?

**Comment by buchen** [comment]
I have created a small snippet. Blue is the StyledLabel, red is the regular label.

As you can see, if the text is an empty String, the height is smaller while for the regular label, it reflects the sizes of the font.

<img width="74" alt="Bildschirmfoto 2019-05-12 um 21 31 23" src="https://user-images.githubusercontent.com/587976/57586940-82b5a100-74fd-11e9-8013-da6299b8a59b.png">

If it is a non-empty String, the height is identical:

<img width="208" alt="Bildschirmfoto 2019-05-12 um 21 34 33" src="https://user-images.githubusercontent.com/587976/57586953-be506b00-74fd-11e9-952f-fabf88cfc4f6.png">

The width is not a problem for at the moment, but it looks like there is some additional space added.


```java
import org.eclipse.jface.resource.FontDescriptor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Font;
import org.eclipse.swt.graphics.Rectangle;
import org.eclipse.swt.layout.RowLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Shell;
import org.greip.label.StyledLabel;

public class TestSnippet
{

    public static void main(String[] args)
    {
        Display display = new Display();
        Shell shell = new Shell(display);
        Rectangle clientArea = shell.getClientArea();

        Font font = FontDescriptor.createFrom(shell.getFont()).setStyle(SWT.NORMAL).increaseHeight(20)
                        .createFont(display);

        String text = "";

        Composite composite = new Composite(shell, SWT.NONE);
        composite.setLayout(new RowLayout());
        composite.setLocation(clientArea.x, clientArea.y);
        
        StyledLabel styledLabel = new StyledLabel(composite, SWT.BORDER);
        styledLabel.setFont(font);
        styledLabel.setText(text);
        styledLabel.setBackground(Display.getDefault().getSystemColor(SWT.COLOR_BLUE));
        styledLabel.pack();

        Label label = new Label(composite, SWT.BORDER);
        label.setFont(font);
        label.setText(text);
        label.setBackground(Display.getDefault().getSystemColor(SWT.COLOR_RED));
        label.pack();

        composite.pack();

        shell.pack();
        shell.open();
        while (!shell.isDisposed())
        {
            if (!display.readAndDispatch())
                display.sleep();
        }
        display.dispose();
    }

}
```

**Comment by greipadmin** [comment]
Ok, I can understand it. Finally, the size is determined by the SWT class TextLayout. This calculates the height differently than the class Label. Even if a space is specified, the heights are not identical. I do not survey the possible side effects of changes. That's why I leave it as it is.

**Comment by buchen** [comment]
> Finally, the size is determined by the SWT class TextLayout.

I tried using TextLayout directly - see code snippet below - and it is calculating the height correctly for an empty string label. When running the sample below, I get 39 pixels, while the height of the StyledText remains at 16 pixels.

I have to admit I am a little lost where this difference comes from.

```java

        Font font = FontDescriptor.createFrom(shell.getFont()).setStyle(SWT.NORMAL).increaseHeight(20)
                        .createFont(display);

        String text = "";

        TextLayout textLayout = new TextLayout(display);
        textLayout.setFont(font);
        textLayout.setText(text);
        System.out.println(textLayout.getBounds());
```

> That's why I leave it as it is.

That is fair.
